# Generated by Django 4.2.1 on 2023-05-09 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'ordering': ['id']},
        ),
    ]
